"""
Tests for database search functions:
database_list()

Credit: tests generated by ChatGPT then checked/added to/tested.
"""

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, clear_mappers

from parkinsons_annotator.modules.models import Base, Variant, Patient, Connector
from parkinsons_annotator.modules.database_search import (
    database_list,
    SearchFieldEmptyError,
    NoMatchingRecordsError
)

# Create database setup fixture
@pytest.fixture(scope="function")
def db_session(monkeypatch):
    """Creates a fresh in-memory DB for each test."""
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    session = Session()

    # Override get_db_session() to return this test session
    from parkinsons_annotator.modules import database_search
    monkeypatch.setattr(database_search, "get_db_session", lambda: session)

    yield session

    session.close()
    engine.dispose()

# Create fixture to add sample data to query:
@pytest.fixture
def seeded_db(db_session):
    """Insert sample Variant / Patient / Connector links."""
    v1 = Variant(
        hgvs="NM_000111.1:c.100A>T",
        vcf_form="17:45983420:A:T",
        gene_symbol="GENE1",
        classification="Pathogenic",
    )

    v2 = Variant(
        hgvs="NM_000222.2:c.200G>C",
        vcf_form="4:45983420:G:C",
        gene_symbol="GENE2",
        classification="Likely benign",
    )

    p1 = Patient(name="Alice")
    p2 = Patient(name="Bob")

    link1 = Connector(patient_name="Alice", variant_vcf_form="17:45983420:A:T")
    link2 = Connector(patient_name="Bob", variant_vcf_form="17:45983420:A:T")
    link3 = Connector(patient_name="Alice", variant_vcf_form="4:45983420:G:C")

    db_session.add_all([v1, v2, p1, p2, link1, link2, link3])
    db_session.commit()

    return db_session

### TESTS ###

def test_missing_search_type(db_session):
    """Raises SearchFieldEmptyError if search_type is not provided."""
    with pytest.raises(SearchFieldEmptyError):
        database_list(search_type=None, search_value="x")


def test_search_variant(seeded_db):
    """Variant search returns Variant object within patient list: [(VariantORM, "Alice"), (VariantORM, "Bob")]"""
    results = database_list(search_type="variant", search_value="NM_000111.1:c.100A>T")

    # Search produces patient list with length 2
    assert len(results) == 2  # Alice + Bob
    # Get results from first tuple (VariantORM, "Alice")
    variant_obj, patient = results[0]

    # Check that VariantORM is a real ORM object has expected attributes of a variant, i.e. HGVS notation
    assert hasattr(variant_obj, "hgvs")
    # Ensure patient name is in list of patients
    assert patient in {"Alice", "Bob"}


def test_search_gene_symbol(seeded_db):
    """Gene symbol search returns all fields correctly"""
    # Search for "GENE1"
    results = database_list(search_type="gene_symbol", search_value="GENE1")

    # Appropriate length of patient list
    assert len(results) == 2  # Alice + Bob

    # Check first item
    row = results[0]

    # Must contain ALL THREE returned fields
    assert "hgvs" in row  # HGVS notation
    assert "name" in row  # patient name
    assert "classification" in row  # ClinVar classification

    # Check specific content is correct
    assert row["hgvs"] in {"NM_000111.1:c.100A>T", "NM_000111.1:c.200G>A"}
    assert row["classification"] in {"Pathogenic", "Likely benign"}


def test_search_patient(seeded_db):
    """Patient search returns all variants correctly"""
    # Search for "Alice"
    results = database_list(search_type="patient_name", search_value="Alice")

    # Alice has both variants
    assert len(results) == 2
    # Confirm each row in results contains 'hgvs' field
    assert all("hgvs" in r for r in results)
    # Confirm each row in results contains 'classification' field
    assert all("classification" in r for r in results)
    # One of the variants is from GENE1
    assert any(r["gene_symbol"] == "GENE1" for r in results)
    # One of the variants is from GENE2
    assert any(r["gene_symbol"] == "GENE2" for r in results)
    # One of the variants is pathogenic
    assert any(r["classification"] == "Pathogenic" for r in results)
    # One of the variants is likely benign
    assert any(r["classification"] == "Likely benign" for r in results)


def test_search_classification(seeded_db):
    """Classification search returns all variants correctly"""
    # Search for "Pathogenic"
    results = database_list(search_type="classification", search_value="None", search_cat="Pathogenic")

    # One variant is pathogenic
    assert len(results) == 1
    # HGVS field is correct
    assert results[0]["hgvs"] == "NM_000111.1:c.100A>T"


def test_no_match_raises(seeded_db):
    """NoMatchingRecordsError raised when no records found"""
    search_cases = [
        #search_type, search_value, search_cat
        ("variant", "NM_000000.0:c.9999A>T", None),
        ("gene_symbol", "FAKEGENE", None),
        ("patient_name", "NOT_A_REAL_PATIENT", None),
        ("classification", None, "FakeClassification")
    ]

    for search_type, search_value, search_cat in search_cases:
        with pytest.raises(NoMatchingRecordsError):
            database_list(
                search_type=search_type,
                search_value=search_value,
                search_cat=search_cat
            )


