"""
Tests for database check functions:
existing_variant_check,
existing_patient_check,
compare_uploaded_vs_existing.

Credit: tests generated by ChatGPT then checked/added to/tested.
"""

import pandas as pd
from types import SimpleNamespace

from parkinsons_annotator.utils.data_checks import (
    existing_variant_check,
    existing_patient_check,
    compare_uploaded_vs_existing,
)
from parkinsons_annotator.modules.models import Variant, Patient

# Classes: Fake SQLAlchemy helpers to give session data/query results

class FakeResult:
    """Mocks session.execute(...).scalars().all() chain"""

    def __init__(self, values):
        self._values = values

    def scalars(self):
        return self

    def all(self):
        return self._values


class FakeSession:
    """
    Minimal fake SQLAlchemy session supporting:
    - session.get()
    - session.execute()
    """

    def __init__(self, variants=None, patients=None, connectors=None):
        self.variants = variants or {}
        self.patients = patients or {}
        self.connectors = connectors or {}

    def get(self, model, key):
        if model is Variant:
            return self.variants.get(key)
        if model is Patient:
            return self.patients.get(key)
        return None

    def execute(self, stmt):
        # stmt filters by Connector.patient_name
        patient_name = stmt.whereclause.right.value
        return FakeResult(self.connectors.get(patient_name, []))


# Test existing_variant_check

def test_existing_variant_check_not_found():
    """Returns None when variant does not exist."""
    # Mock DB connection
    session = FakeSession()

    # Search for variant that does not exist
    result = existing_variant_check("1:1:A:T", session)

    assert result is None


def test_existing_variant_check_found():
    """Returns variant data dict when variant exists."""

    # Test variant data for check to find
    variant = SimpleNamespace(
        vcf_form="1:1:A:T",
        hgvs="HGVS1",
        clinvar_id="CV1",
        classification="Pathogenic",
        gene_symbol="GENE1",
        cdna_change="c.1A>T",
        clinvar_accession="ACC1",
        num_records="5",
        review_status="reviewed",
        associated_condition="Condition",
        clinvar_url="http://clinvar"
    )

    session = FakeSession(
        variants={"1:1:A:T": variant}
    )

    result = existing_variant_check("1:1:A:T", session)

    # Check data identified correctly
    assert result["vcf_form"] == "1:1:A:T"
    assert result["hgvs"] == "HGVS1"
    assert result["gene_symbol"] == "GENE1"


# Test existing_patient_check

def test_existing_patient_check_patient_not_found():
    """Returns None when patient is not in DB."""
    session = FakeSession()

    result = existing_patient_check("Alice", session)

    assert result is None


def test_existing_patient_check_patient_found():
    """Returns list of variant VCF forms for existing patient."""
    session = FakeSession(
        patients={"Alice": SimpleNamespace(name="Alice")},
        connectors={"Alice": ["1:1:A:T", "2:2:G:C"]}
    )

    result = existing_patient_check("Alice", session)

    assert result == ["1:1:A:T", "2:2:G:C"]


# Test compare_uploaded_vs_existing

def test_compare_uploaded_vs_existing_patient_not_in_db():
    """Patient does not exist returns exists=False."""

    # Data to compare with DB (does not exist in DB so check should return False)
    df = pd.DataFrame([
        {"chromosome": "1", "position": 1, "ref": "A", "alt": "T"},
        {"chromosome": "2", "position": 2, "ref": "G", "alt": "C"},
    ])

    session = FakeSession()

    # Call check
    result = compare_uploaded_vs_existing("Alice", df, session)

    # Test that check can identify patient does not exist, and that uploaded variants are parsed as expected
    assert result["exists"] is False
    assert result["identical"] is False
    assert result["uploaded_variants"] == ["1:1:A:T", "2:2:G:C"]
    assert result["existing_variants"] == []


def test_compare_uploaded_vs_existing_identical_variants():
    """Uploaded variants exactly match existing variants."""
    # Matching data to a patient in DB
    df = pd.DataFrame([
        {"chromosome": "1", "position": 1, "ref": "A", "alt": "T"}
    ])

    # Patient with identical data
    session = FakeSession(
        patients={"Alice": SimpleNamespace(name="Alice")},
        connectors={"Alice": ["1:1:A:T"]}
    )

    # Call check
    result = compare_uploaded_vs_existing("Alice", df, session)

    # Test can see that patient exists and uploaded variants match existing variants
    assert result["exists"] is True
    assert result["identical"] is True


def test_compare_uploaded_vs_existing_different_variants():
    """Uploaded variants differ from existing variants."""
    # Uploaded variant differs from existing variant
    df = pd.DataFrame([
        {"chromosome": "3", "position": 3, "ref": "C", "alt": "G"}
    ])

    session = FakeSession(
        patients={"Alice": SimpleNamespace(name="Alice")},
        connectors={"Alice": ["1:1:A:T"]}
    )

    result = compare_uploaded_vs_existing("Alice", df, session)

    # Patient exists, but uploaded variant differs from existing variant
    assert result["exists"] is True
    assert result["identical"] is False
    assert result["uploaded_variants"] == ["3:3:C:G"]
    assert result["existing_variants"] == ["1:1:A:T"]
