from flask import has_request_context
from parkinsons_annotator.modules.db import get_db_session
from parkinsons_annotator.modules.models import Variant, Patient, Connector
from sqlalchemy import select
from parkinsons_annotator.logger import logger

# Check whether variant has been uploaded before
def existing_variant_check(vcf_form:str, session):
    """
    Checks whether variant already exists in database, if so, returns the variant data to allow the data extraction
    script to skip API calls.

    Args:
        vcf_form: Genomic notation of variant
        session: Database session inherited from load_and_insert_ data function where check is performed

    Returns:
        Dictionary of variant data, or None if variant not found

    """

    # Use get() method to retrieve variant object from database using primary key
    variant = session.get(Variant, vcf_form)

    # Return None if variant not found
    if not variant:
        logger.debug(f"Variant {vcf_form} not yet in database")
        return None

    # Otherwise, return variant data
    logger.info(f"Found variant {vcf_form} in database.")
    return {
        "hgvs": variant.hgvs,
        "vcf_form": variant.vcf_form,
        "clinvar_id": variant.clinvar_id,
        "classification": variant.classification,
        "gene_symbol": variant.gene_symbol,
        "cdna_change": variant.cdna_change,
        "clinvar_accession": variant.clinvar_accession,
        "num_records": variant.num_records,
        "review_status": variant.review_status,
        "associated_condition": variant.associated_condition,
        "clinvar_url": variant.clinvar_url
    }


# Check whether patient with the same name has been uploaded before and whether variants are the same
def existing_patient_check(patient_name:str,session):
    """
    Check whether patient with the same name has been uploaded before and return variants for patient

    Args:
        patient_name:
        session:

    Returns:
        variant_list: list of variants(str) for patient

    """

    # Check if patient exists in database: use get() method to retrieve patient object from database using primary key
    patient = session.get(Patient, patient_name)
    if not patient:
        logger.debug(f"Patient '{patient_name}' does not yet exist in database.")
        return None

    # Patient exists in database
    logger.info(f"Patient '{patient_name}' already exists in database.")
    # Retrieve all variants for patient found in database
    stmt = select(Connector.variant_vcf_form).where(Connector.patient_name == patient_name)
    # Use scalars to get simple list of strings
    variant_list = session.execute(stmt).scalars().all()

    logger.info(f"Found {len(variant_list)} variants for patient '{patient_name}'")
    return variant_list


def compare_uploaded_vs_existing(patient_name: str, df, session):
    """
    Compare uploaded variants vs DB-stored variants for this patient.

    Args:
        patient_name (str): Patient name
        df (pd.DataFrame): DataFrame containing variant data for a patient
        session: Database session inherited from load_and_insert_ data function where check is performed

    Returns:
        Dictionary containing comparison results
        {
          "exists": bool,        # patient exists in DB
          "identical": bool,     # sets identical
          "uploaded_variants": [..],  # list of uploaded variants
          "existing_variants": [..]  # list of variants in DB
        }

    Credit: This function was generated by chatGPT then checked and tested.
    """
    # Check if patient exists; get variant list for patient if so
    existing = existing_patient_check(patient_name,session)

    # Get list of uploaded variants from patient DataFrame generated from CSV/VCF
    uploaded = df.apply(
        lambda r: f"{r.chromosome}:{r.position}:{r.ref}:{r.alt}", axis=1
    ).tolist()

    # If patient does not exist in database, return comparison results with no variants
    if existing is None:
        return {
            "exists": False,
            "identical": False,
            "uploaded_variants": uploaded,
            "existing_variants": []
        }

    # Check if uploaded variants are identical to existing variants
    identical = (set(uploaded) == set(existing))

    return {
        "exists": True,
        "identical": identical,
        "uploaded_variants": uploaded,
        "existing_variants": existing
    }
