"""
This utility function parses genomic notation strings into chromosome, position, reference, and alternate alleles.

Supported formats:
        - chr7:140453136A>T
        - chr7:140453136:A:T
        - 7:140453136:A:T

    Returns:
        tuple: (chromosome, position, ref, alt)

The script itself was generated by chatGPT and then manually checked.
"""
import re

def parse_genomic_notation(notation):
    """
    Parse a genomic notation string into chromosome, position, reference, and alternate alleles.

    Supported formats:
        - chr7:140453136A>T
        - chr7:140453136:A:T
        - 7:140453136:A:T

    Returns:
        tuple: (chromosome, position, ref, alt)
    """
    # Normalize by removing "chr" prefix if present
    notation = notation.replace("chr", "")

    # Split by common separators (: or >)
    # Handle patterns like 7:140453136:A:T or 7:140453136A>T
    match = re.match(r"(\d+):(\d+):?([A-Za-z])[:>]([A-Za-z])", notation)
    if not match:
        raise ValueError(f"Invalid genomic notation format: {notation}")

    chr_value = int(match.group(1))
    pos_value = int(match.group(2))
    ref_value = match.group(3).upper()
    alt_value = match.group(4).upper()

    return chr_value, pos_value, ref_value, alt_value
